apiVersion: v1
kind: ServiceAccount
metadata:
  name: aim-service-account
  namespace: aim
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aim-role
  namespace: aim
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aim-role-binding
  namespace: aim
subjects:
- kind: ServiceAccount
  name: aim-service-account
  namespace: aim
roleRef:
  kind: Role
  name: aim-role
  apiGroup: rbac.authorization.k8s.io

